---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - git
      - gnupg
      - software-properties-common
      - curl
    state: present
    update_cache: true
    cache_valid_time: "{{ terraform_cache_valid_time }}"
  become: true
  tags:
    - terraform
    - terraform.dependencies

- name: Add terraform key to apt
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: true
  notify: Update apt
  tags:
    - terraform
    - terraform.dependencies

- name: Add terraform repo to apt
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64] https://apt.releases.hashicorp.com
      {{
        ansible_facts["ansible_lsb"].codename |
        default(ansible_distribution_release)
      }}
      main
    state: present
  become: true
  notify: Update apt
  tags:
    - terraform
    - terraform.dependencies

- name: Force all notified handlers to run
  ansible.builtin.meta: flush_handlers
  tags:
    - always

- name: Install terraform
  ansible.builtin.apt:
    name:
      - terraform
    state: present
  become: true
  tags:
    - terraform
    - terraform.dependencies

- name: Create terraform folder structure
  ansible.builtin.file:
    path: /home/ansible/terraform
    state: directory
    mode: u=rwx,g=rx,o=rx
  tags:
    - terraform
    - terraform.apply

- name: Git checkout terraform plan
  ansible.builtin.git:
    repo: "{{ terraform_repo_url }}"
    dest: "{{ terraform_repo_dir }}"
    version: main
  tags:
    - terraform
    - terraform.apply

- name: Execute terraform plan
  community.general.terraform:
    project_path: /home/ansible/terraform/spoke-network
    state: "{{ terraform_state }}"
    variables: "{{ terraform_variables | default( {} ) }}"
    force_init: true
  tags:
    - terraform
    - terraform.apply
    - molecule-notest
...
